name: Frontend CI Practice

on: push

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Display project files
        run: ls

      - name: Display current directory
        run: pwd

      - name: Read HTML file
        run: cat code./index.html

      - name: Validate HTML title
        run: grep "<title>" code/index.html


      - name: Success message
        run: echo "Workflow completed successfully"